{
 "title": "C* Cluster Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "30s,1m,5m,10m,15m,30m,1h,2h,3h,6h,12h,24h"
   },
   { "name": "jobname", "label": "Job name of Cassandra exporter", "query": "${VAR_JOBNAME}" },
   {
    "name": "instance",
    "query": "label_values(up{job=\"$jobname\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (clientrequest) (irate(cassandra_clientrequest_totallatency{instance=~\"$instance\",clientrequest=~\"Write-.*\"}[$rate])) / sum by (clientrequest) (irate(cassandra_clientrequest_latency{instance=~\"$instance\",clientrequest=~\"Write-.*\"}[$rate]))",
     "legendFormat": "{{ clientrequest }}"
    }
   ]
  },
  {
   "title": "Write Requests By Consistency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (clientrequest) (irate(cassandra_clientrequest_latency{instance=~\"$instance\",clientrequest=~\"Write.*\", clientrequest!=\"Write\"}[$rate]))",
     "legendFormat": "{{ clientrequest }} "
    }
   ]
  },
  {
   "title": "Write Requests by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_latency{instance=~\"$instance\",clientrequest=\"Write\"}[$rate]))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (clientrequest) (irate(cassandra_clientrequest_totallatency{instance=~\"$instance\",clientrequest=~\"Read-.*\"}[$rate])) / sum by (clientrequest) (irate(cassandra_clientrequest_latency{instance=~\"$instance\",clientrequest=~\"Read-.*\"}[$rate]))",
     "legendFormat": "{{ clientrequest }}"
    }
   ]
  },
  {
   "title": "Read Requests By Consistency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (clientrequest) (irate(cassandra_clientrequest_latency{instance=~\"$instance\",clientrequest=~\"Read.*\", clientrequest!=\"Read\"}[$rate]))",
     "legendFormat": "{{ clientrequest }} "
    }
   ]
  },
  {
   "title": "Read Requests by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_latency{instance=~\"$instance\",clientrequest=\"Read\"}[$rate]))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadpools) (sum_over_time(cassandra_threadpools_currentlyblockedtasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ threadpools }}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadpools) (sum_over_time(cassandra_threadpools_pendingtasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ threadpools }}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadpools) (sum_over_time(cassandra_threadpools_activetasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ threadpools }}"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (droppedmessage) (increase(cassandra_droppedmessage_dropped{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ droppedmessage }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cache) (cassandra_cache_oneminutehitrate{instance=~\"$instance\"})",
     "legendFormat": "{{ cache }}"
    }
   ]
  },
  {
   "title": "Request Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (clientrequest) (increase(cassandra_clientrequest_timeouts{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ clientrequest }}"
    }
   ]
  },
  {
   "title": "Bytes Compacted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_compaction_bytescompacted{instance=~\"$instance\"}[$rate])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Native Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\",area=\"heap\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hints Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_storage_totalhints{instance=~\"$instance\"}[$rate])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_connection_gossipmessagecompletedtasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}